# Derived from Nicolas Iooss: https://github.com/fishilico/selinux-refpolicy-patched/blob/travis-upstream/.travis.yml

language: generic

env:
  - TYPE=standard DISTRO=redhat MONOLITHIC=y SYSTEMD=y
  - TYPE=standard DISTRO=redhat MONOLITHIC=n SYSTEMD=y
  - TYPE=standard DISTRO=debian MONOLITHIC=y SYSTEMD=y
  - TYPE=standard DISTRO=debian MONOLITHIC=n SYSTEMD=y
  - TYPE=standard DISTRO=gentoo MONOLITHIC=y SYSTEMD=n
  - TYPE=standard DISTRO=gentoo MONOLITHIC=n SYSTEMD=n
  - TYPE=mcs DISTRO=redhat MONOLITHIC=y SYSTEMD=y
  - TYPE=mcs DISTRO=redhat MONOLITHIC=n SYSTEMD=y
  - TYPE=mcs DISTRO=debian MONOLITHIC=y SYSTEMD=y
  - TYPE=mcs DISTRO=debian MONOLITHIC=n SYSTEMD=y
  - TYPE=mcs DISTRO=gentoo MONOLITHIC=y SYSTEMD=n
  - TYPE=mcs DISTRO=gentoo MONOLITHIC=n SYSTEMD=n
  - TYPE=mls DISTRO=redhat MONOLITHIC=y SYSTEMD=y
  - TYPE=mls DISTRO=redhat MONOLITHIC=n SYSTEMD=y
  - TYPE=mls DISTRO=debian MONOLITHIC=y SYSTEMD=y
  - TYPE=mls DISTRO=debian MONOLITHIC=n SYSTEMD=y
  - TYPE=mls DISTRO=gentoo MONOLITHIC=y SYSTEMD=n
  - TYPE=mls DISTRO=gentoo MONOLITHIC=n SYSTEMD=n

# Use Travis-CI Trusty environments (https://docs.travis-ci.com/user/trusty-ci-environment/)
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - policycoreutils


script:
  - lsb_release -a

  # Check the version of checkpolicy which is used
  - checkpolicy -V

  # Drop build.conf settings to listen to env vars
  - sed -r -i -e '/(MONOLITHIC|TYPE|DISTRO|SYSTEMD)/d' build.conf

  # Build!
  - echo $TYPE $DISTRO $MONOLITHIC
  - make bare
  - make conf
  - make
  - make validate
